development:
  adapter: postgresql
  database: browet_demo_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: browet_demo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: browet_demo_production
  pool: 5
  timeout: 5000