# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106e56d796a7aad36b8b162ccd0f6f18a0d25c7774c307562fe96af6a22014af8db51636c4762696d21ca8d271f4f3941a3d26327dfa77bedbbae37a1817938d

test:
  secret_key_base: 8839ddac9d4b44541db1142b51d06ce9856b5ee3af58fef0dcd07d7718fc21db12dbf71aa7234d2aa8ce12c4b34c4ab126362ae2310d8dcbfceae11c634d211f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
